routes/web.php
Route::get('password/edit', 'Admin\Auth\ForgotPasswordController@passworUpdateForm')->name('password.edit');
Route::post('password/update', 'Admin\Auth\ForgotPasswordController@updatePassword')->name('password.update');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

	Route::get('driver/document/{id}', 'Driver\DriverController@driverDocument')->name('driver.document');
	Route::get('driver/upload/document/{user_id}/{doc_id}', 'Driver\DriverController@driverDocumentIndex')->name('driver.upload.document');
	Route::post('driver/update/document', 'Driver\DriverController@driverDocumentUpdate')->name('driver.update.document');

	Route::post('logout', 'Auth\LoginController@logout')->name('logout');
	Route::resource('dashboard', 'Dashboard\DashboardController');
	Route::get('dashboard/details/{id}/{param}', 'Dashboard\DashboardController@dashboardRequestDetails')->name('dashboard.details');

	Route::get('password', 'AdminController@password')->name('password');
	Route::post('password/update', 'AdminController@changePassword')->name('password.update');

	Route::get('profile', 'AdminController@profile')->name('profile');
	Route::post('profile/update', 'AdminController@profileUpdate')->name('profile.update');

	Route::resource('setting', 'Setting\SettingController');

	Route::get('settings/payment', 'Setting\SettingController@paymentSetting')->name('settings.payment');

	Route::get('settings/live', 'Setting\SettingController@liveStripe')->name('settings.live');

	Route::get('settings/demo', 'Setting\SettingController@demoStripe')->name('settings.demo');

	Route::get('stripemode/update', 'Setting\SettingController@updateStripeMode')->name('stripemode.update');

	Route::post('settings/payment/update', 'Setting\SettingController@updateStripe')->name('settings.payment.update');

	//banner text..........
	Route::get('settings/banner-text', 'Setting\SettingController@bannerText')->name('settings.banner-text');

	Route::put('settings/banner-text/update/{id}', 'Setting\SettingController@bannerTextUpdate')->name('settings.banner-text.update');
	//..................

	//about us..........
	Route::get('settings/about-us', 'Setting\SettingController@aboutUS')->name('settings.about-us');

	Route::put('settings/about-us/update/{id}', 'Setting\SettingController@aboutUsUpdate')->name('settings.about-us.update');
	//..................

	//app-paragraph..........
	Route::get('settings/app-paragraph', 'Setting\SettingController@appParagraph')->name('settings.app-paragraph');

	Route::put('settings/app-paragraph/update/{id}', 'Setting\SettingController@appParagraphUpdate')->name('settings.app-paragraph.update');
	//..................

	Route::get('privacy/policy', 'Setting\SettingController@privacyPolicy')->name('privacy.policy');
	Route::put('privacy-policy/update/{id}', 'Setting\SettingController@privacyPolicyUpdate')->name('privacy-policy.update');

	Route::resource('document', 'Document\DocumentController');
	Route::get('document/active/{id}', 'Document\DocumentController@changeStatus')->name('document.active');

	Route::resource('service', 'Service\ServiceTypeController');

	Route::resource('vehicle', 'Vehicle\VehicleController');
	Route::post('vehicles','Vehicle\VehicleController@getVehicles')->name('dataProcessing');

	Route::resource('passenger', 'Passenger\PassengerController');
	Route::post('ajax-passenger','Passenger\PassengerController@ajaxPassenger')->name('ajax-passenger');

	Route::get('get/vehicle', 'Driver\DriverController@getVehicle')->name('get.vehicle');

	Route::resource('driver', 'Driver\DriverController');
	Route::post('ajax-driver','Driver\DriverController@ajaxDriver')->name('ajax-driver');

	Route::get('drivers/document/{id}', 'Driver\DriverController@listDriverDocument')->name('drivers.document');
	Route::get('drivers/service-type/{id}', 'Driver\DriverController@listDriverServiceType')->name('drivers.service-type');
	Route::get('driver/document/verification/{id}', 'Driver\DriverController@driverDocumentVerification')->name('driver.document.verification');
	Route::get('driver/activation/{id}', 'Driver\DriverController@driverActivationProcess')->name('driver.activation');
	// Route::get('driver/carimages/{id}', 'Driver\DriverController@driverCarImages')->name('driver.carimages');
	// Route::get('driver/transaction/{id}', 'Driver\DriverController@driverTransaction')->name('driver.transaction');
	Route::post('driver/document-reason/{id}', 'Driver\DriverController@documentVerificationReason')->name('driver.document-reason');

	Route::get('request/all', 'DriveReport\DriveReportController@allRequest')->name('request.all');
	Route::post('ajax-all-request', 'DriveReport\DriveReportController@ajaxAllRequest')->name('ajax-all-request');
	Route::get('request/nofound', 'DriveReport\DriveReportController@noServiceFoundRequest')->name('request.nofound');
	Route::post('ajax-noservice-found', 'DriveReport\DriveReportController@ajaxNoServiceFoundRequest')->name('ajax-noservice-found');

	Route::get('request/rejected', 'DriveReport\DriveReportController@rejectedRequest')->name('request.rejected');
	Route::post('ajax-rejected-request', 'DriveReport\DriveReportController@ajaxRejectedRequest')->name('ajax-rejected-request');

	Route::get('request/schedule', 'DriveReport\DriveReportController@scheduleRequest')->name('request.schedule');
	Route::post('ajax-schedule-request', 'DriveReport\DriveReportController@ajaxScheduleRequest')->name('ajax-schedule-request');

	Route::get('request/details/{id}/{param}', 'DriveReport\DriveReportController@requestDetails')->name('request.details');

	Route::get('chat/support', 'Chat\ChatSupportController@chatSupport')->name('chat.support');

	 //report issue
	Route::get('reportIssue/driver/subject/list', 'ReportIssue\ReportController@driverSubjectList')->name('reportIssue.driver.subject.list');
	Route::post('reportIssue/driver/subject/add', 'ReportIssue\ReportController@driverSubjectAdd')->name('reportIssue.driver.subject.add');
	Route::get('reportIssue/driver/subject/edit/{id}', 'ReportIssue\ReportController@driverSubjectEdit')->name('reportIssue.driver.subject.edit');
	Route::put('reportIssue/driver/subject/update/{id}', 'ReportIssue\ReportController@driverSubjectUpdate')->name('reportIssue.driver.subject.update');

	Route::get('reportIssue/customer/subject/list', 'ReportIssue\ReportController@customerSubjectList')->name('reportIssue.customer.subject.list');
	Route::post('reportIssue/customer/subject/add', 'ReportIssue\ReportController@customerSubjectAdd')->name('reportIssue.customer.subject.add');
	Route::get('reportIssue/customer/subject/edit/{id}', 'ReportIssue\ReportController@customerSubjectEdit')->name('reportIssue.customer.subject.edit');
	Route::put('reportIssue/customer/subject/update/{id}', 'ReportIssue\ReportController@customerSubjectUpdate')->name('reportIssue.customer.subject.update');

	Route::get('reportIssue/driver/list', 'ReportIssue\ReportController@driverReportIssueList')->name('reportIssue.driver.list');
	Route::get('reportIssue/customer/list', 'ReportIssue\ReportController@customerReportIssueList')->name('reportIssue.customer.list');
	Route::get('reportIssue/details/{id}/{param}', 'ReportIssue\ReportController@reportIssueDetails')->name('reportIssue.details');
	// Route::get('reportIssue/customer/details/{id}/{param}', 'ReportIssue\ReportController@customerReportIssueDetails')->name('reportIssue.customer.details');

	//review rating
	Route::get('drivers/review-rating/{id}', 'Driver\DriverController@driverRatingReview')->name('drivers.review-rating');
	Route::get('passenger/review-rating/{id}', 'Passenger\PassengerController@passengerRatingReview')->name('passenger.review-rating');

	//passenger trip
	Route::get('passenger/trip/history/{id}', 'Passenger\TripController@tripIndex')->name("passenger.trip.history");
	Route::post('ajax-passenger-trips', 'Passenger\TripController@ajaxPassengerTrips')->name('ajax-passenger-trips');
	Route::get('passenger/trip/history/details/{id}/{param}', 'Passenger\TripController@tripDetails')->name('passenger.trip.history.details');

	 //Driver trip
	Route::get('driver/trip/history/{id}', 'Driver\DriverTripController@tripIndex')->name("driver.trip.history");
	Route::post('ajax-driver-trips', 'Driver\DriverTripController@ajaxDriverTrips')->name('ajax-driver-trips');
	Route::get('driver/trip/history/details/{id}/{param}', 'Driver\DriverTripController@tripDetails')->name('driver.trip.history.details');

	Route::resource('promocode', 'Promocode\PromocodeController');

	//make model year
	Route::get('get/admin/make', 'Driver\DriverController@getAdminMake')->name("get.admin.make");
	Route::post('get/admin/model', 'Driver\DriverController@getAdminModel')->name("get.admin.model");
	Route::post('get/admin/year', 'Driver\DriverController@getAdminYear')->name("get.admin.year");
	
	// Route::resource('credit', 'CreditPackage\CreditPackageController');
	// Route::resource('email-control', 'Email\EmailController');

	// //Driver Document verification.........

	// Route::get('driver/check-document/{id}', 'Driver\DocumentVerificationController@allDocumentCheck')->name('driver.check-document');
	// Route::get('driver/rating-review/{id}', 'Driver\DriverRatingController@driverRatingReview')->name('driver.rating-review');
	// Route::get('driver/runcron/{id}', 'Driver\DocumentVerificationController@cronjobToMailDriver')->name('driver.runcron');
	// //.....................................

	// Route::get('driver/rating-list/{id}/{last_id}/{first_id}', 'Driver\DriverRatingController@ratingList')->name('driver.rating-list');
	// Route::post('driver/reason/{id}', 'Driver\DriverController@driverInactiveBannedReason')->name('driver.reason');
	// Route::get('driver/rating-search/{id}', 'Driver\DriverRatingController@searchRating')->name('driver.rating-search');

	// Route::post('driver/rating-alert/{id}', 'Driver\DriverRatingController@driverRatingAlert')->name('driver.rating-alert');
	// //payment

app/Http/Controllers/Api/Passenger/EmergencyContactController.php
<?php

resources/views/admin/passenger/create.blade.php
@extends('admin.layout.base')

@section('title', 'Add Customer ')

@section('content')

<div class="content-area py-1">
    <div class="container-fluid">
    	<div class="box box-block bg-white">
    	    <a href="{{ route('admin.passenger.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>

			<h5 style="margin-bottom: 2em;">Add Customer</h5>

            <form class="form-horizontal" action="{{route('admin.passenger.store' )}}" method="POST" enctype="multipart/form-data" role="form">
            	{{csrf_field()}}
            	
				<div class="form-group row">
					<label for="first_name" class="col-xs-2 col-form-label">First Name</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" name="first_name" value="{{ old('first_name') }}"  id="first_name" placeholder="First Name" required>
					</div>
				</div>

				<div class="form-group row">
					<label for="last_name" class="col-xs-2 col-form-label">Last Name</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" name="last_name" value="{{ old('last_name') }}" id="last_name" placeholder="Last Name" required>
					</div>
				</div>

				<div class="form-group row">
					<label for="email" class="col-xs-2 col-form-label">Email</label>
					<div class="col-xs-10">
						<input class="form-control" type="email" name="email" value="{{ old('email') }}" id="email" placeholder="Email">
					</div>
				</div>

				<div class="form-group row">
					<label for="picture" class="col-xs-2 col-form-label">Picture</label>
					<div class="col-xs-10">
						<input type="file" accept="image/*" name="picture" class="dropify form-control-file" id="picture" aria-describedby="fileHelp">
					</div>
				</div>
				
				<div class="form-group row">
					<label for="mobile_no" class="col-xs-2 col-form-label">Mobile</label>
					<div class="col-xs-10">
						<input class="form-control" type="tel" name="mobile_no" id="mobile_no" placeholder="Mobile No" required>
						<input type="hidden" name="code" id="code">
					</div>
				</div>

				<div class="form-group row">
					<label for="dob" class="col-xs-2 col-form-label">Date of Birth</label>
					<div class="col-xs-10">
						<input class="form-control" type="date" name="dob" value="{{ old('dob') }}" id="dob">
					</div>
				</div>
				<div class="form-group row">
					<label for="gender" class="col-xs-2 col-form-label">Gender</label>
					<div class="col-xs-10">
						<input type="radio" id="Male" name="gender" value="Male">
						<label for="Male">Male</label><br>
						<input type="radio" id="Female" name="gender" value="Female">
						<label for="Female">Female</label><br>
						<input type="radio" id="Transgender" name="gender" value="Transgender">
						<label for="Transgender">Transgender</label>
					</div>
				</div>

				<div class="form-group row password">
					<label for="password" class="col-xs-2 col-form-label">Password</label>
					<div class="col-xs-10">
						<input class="form-control" type="password" name="password" id="password" placeholder="Password" required>
					</div>
				</div>
				<div class="form-group row">
					<label for="password_confirmation" class="col-xs-2 col-form-label">Password Confirmation</label>
					<div class="col-xs-10">
						<input class="form-control" type="password" name="password_confirmation" value="{{ old('password_confirmation') }}" id="password_confirmation" placeholder="Re-type Password">
					</div>
				</div>

				<div class="form-group row">
					<label for="zipcode" class="col-xs-2 col-form-label"></label>
					<div class="col-xs-10">
						<button type="submit" class="btn btn-primary">Add Customer</button>
						<a href="{{route('admin.passenger.index')}}" class="btn btn-default">Cancel</a>
					</div>
				</div>
			</form>
		</div>
    </div>
</div>
<style type="text/css">.iti { width: 100%; }</style>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
 <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/16.0.15/css/intlTelInput.css">
 <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/16.0.15/js/intlTelInput-jquery.min.js"></script>
 <script>
	jq = jQuery.noConflict();
    use :
   		var s = jq("#mobile_no").intlTelInput({
			autoPlaceholder: 'polite',
   			separateDialCode: true,
   			formatOnDisplay: true,
   			initialCountry: 'ng'
   			//utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/16.0.15/js/utils.js"
   		});

   	insteadof :
   		var d = jq("#mobile_no").intlTelInput("getSelectedCountryData").dialCode;
   		jq("#code").val(d);
		jq(document).on('countrychange', function (e, countryData) {
        	jq("#code").val((jq("#mobile_no").intlTelInput("getSelectedCountryData").dialCode));
    	});
</script>
@endsection

resources/views/admin/passenger/edit.blade.php
@extends('admin.layout.base')

@section('title', 'Update Customer')

@section('content')

<div class="content-area py-1">
    <div class="container-fluid">
    	<div class="box box-block bg-white">
    	    <a href="{{ route('admin.passenger.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>

			<h5 style="margin-bottom: 2em;">Update Customer</h5>

            <form class="form-horizontal" action="{{route('admin.passenger.update', $passenger->id )}}" method="POST" enctype="multipart/form-data" role="form">
            	{{csrf_field()}}
            	<input type="hidden" name="_method" value="PATCH">
				<div class="form-group row">
					<label for="first_name" class="col-xs-2 col-form-label">First Name</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" value="{{ $passenger->passenger_profile->first_name }}" name="first_name" required id="first_name" placeholder="First Name">
					</div>
				</div>

				<div class="form-group row">
					<label for="last_name" class="col-xs-2 col-form-label">Last Name</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" value="{{ $passenger->passenger_profile->last_name }}" name="last_name" required id="last_name" placeholder="Last Name">
					</div>
				</div>

				<div class="form-group row">
					<label for="email" class="col-xs-2 col-form-label">Email</label>
					<div class="col-xs-10">
						<input class="form-control" type="email" value="{{ $passenger->passenger_profile->email_id }}" name="email" id="email" placeholder="Email">
					</div>
				</div>

				<div class="form-group row">
					<label for="picture" class="col-xs-2 col-form-label">Picture</label>
					<div class="col-xs-10">
					@if(isset($passenger->passenger_profile->picture))
                    	@if(File::exists(storage_path('app/public' .str_replace("storage", "", $passenger->passenger_profile->picture))))
                            <img style="height: 90px; margin-bottom: 15px;" src="{{URL::asset($passenger->passenger_profile->picture)}}">
                        @else
                            <img src="{{$passenger->passenger_profile->picture}}" style="height: 60px; margin-bottom: 15px;">
                        @endif
                    @else
                     	<img style="height: 60px; margin-bottom: 15px;" src="{{URL::asset('asset/NO_IMG.png')}}">
                    @endif
						<input type="file" accept="image/*" name="picture" class="dropify form-control-file" id="picture" aria-describedby="fileHelp">
					</div>
				</div>

				<div class="form-group row">
					<label for="mobile" class="col-xs-2 col-form-label">Mobile</label>
					<div class="col-xs-10">
						<input class="form-control" type="tel" value="{{ $passenger->passenger_profile->mobile_no }}" name="mobile" id="mobile" placeholder="Mobile No" required>
						<input type="hidden" name="code" id="code" value="{{$passenger->passenger_profile->isd_code}}">
					</div>
				</div>

				<div class="form-group row">
					<label for="dob" class="col-xs-2 col-form-label">Date of Birth</label>
					<div class="col-xs-10">
						<input class="form-control" type="date" name="dob" value="{{ $passenger->passenger_profile->dob }}" id="dob">
					</div>
				</div>
				<div class="form-group row">
					<label for="gender" class="col-xs-2 col-form-label">Gender</label>
					<div class="col-xs-10">
						<input type="radio" id="Male" name="gender" value="Male" {{ $passenger->passenger_profile->gender == 'Male' ? 'checked' : ''}}>
						<label for="Male">Male</label><br>
						<input type="radio" id="Female" name="gender" value="Female" {{ $passenger->passenger_profile->gender == 'Female' ? 'checked' : ''}}>
						<label for="Female">Female</label><br>
						<input type="radio" id="Transgender" name="gender" value="Transgender" {{ $passenger->passenger_profile->gender == 'Transgender' ? 'checked' : ''}}>
						<label for="Transgender">Transgender</label>
					</div>
				</div>

				<div class="form-group row">
					<label for="zipcode" class="col-xs-2 col-form-label"></label>
					<div class="col-xs-10">
						<button type="submit" class="btn btn-primary">Update Customer</button>
						<a href="{{route('admin.passenger.index')}}" class="btn btn-default">Cancel</a>
					</div>
				</div>
			</form>
		</div>
    </div>
</div>
<style type="text/css">
	.iti { width: 100%; }
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/16.0.15/css/intlTelInput.css">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/16.0.15/js/intlTelInput-jquery.min.js"></script>
<script>
	jq = jQuery.noConflict();
    use :
   		var s = jq("#mobile").intlTelInput({
   			autoPlaceholder: 'polite',
   			separateDialCode: true,
   			formatOnDisplay: true,
   			initialCountry: 'ng'
   		});
   	insteadof :
   		var countryData = window.intlTelInputGlobals.getCountryData();
   		var iso2;
		var isdcode = jq("#code").val();
		for (var i = 0; i < countryData.length; i++) {
			if (countryData[i].dialCode == parseInt(isdcode)){
				iso2 = countryData[i].iso2;
				break;
			}
		}
		if(iso2){
			jq("#mobile").intlTelInput("setCountry", iso2);
		}
		jq(document).on('countrychange', function (e, countryData) {
        	jq("#code").val((jq("#mobile").intlTelInput("getSelectedCountryData").dialCode));
    	});
</script>
@endsection

resources/views/admin/passenger/index.blade.php
@extends('admin.layout.base')

@section('title', 'Customers')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5 class="mb-1">
                Customers
            </h5>
            <a href="{{ route('admin.passenger.create') }}" style="margin-left: 1em;" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Add New Customer</a>
            <table class="table table-striped table-bordered dataTable" id="table-pass">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Customer Name</th>
                      {{--   <th>Last Name</th> --}}
                        <th>Email</th>
                        <th>Mobile</th>
                        <th>Action</th>
                    </tr>
                </thead>
                {{-- <tbody>
                    @foreach($passengers as $index => $passenger)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $passenger->first_name }}</td>
                        <td>{{ $passenger->last_name }}</td>
                        <td>{{ $passenger->email }}</td>
                        <td>{{ $passenger->mobile }}</td>
                        @if($passenger->passenger_profile != null)
                        <td>{{ $passenger->passenger_profile->rating }}</td>
                        @else
                        <td></td>
                        @endif
                        <td>
                            <a href="{{ route('admin.passenger.edit', $passenger->id) }}" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a>
                            <form action="{{ route('admin.passenger.destroy', $passenger->id) }}" method="POST">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="DELETE">
                                <button class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash"></i> Delete</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody> --}}
                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Customer Name</th>
                        {{-- <th>Last Name</th> --}}
                        <th>Email</th>
                        <th>Mobile</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@endsection
@section('scripts')
    <script>
        $('#table-pass').DataTable( {
            "order": [[0, 'desc']],
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url":"{{route('admin.ajax-passenger')}}",
                "dataType":"json",
                "type":"POST",
                "data":{"_token":"<?= csrf_token() ?>"}
            },
            "columns":[
                {"data":"id"},
                {"data":"passenger_name"},
                {"data":"email"},
                {"data":"mobile"},
                {"data":"action","searchable":false,"orderable":false}
            ],
            responsive: true,
            dom: 'Bfrtip',
            buttons: [
                'copyHtml5',
                'excelHtml5',
                'csvHtml5',
                'pdfHtml5'
            ],
        } );
    </script>
@endsection

resources/views/admin/passenger/trip-history.blade.php
@extends('admin.layout.base')

@section('title', 'Trip History ')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5 class="mb-1">Trip History</h5>
            <a href="{{ route('admin.passenger.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>

            <table class="table table-striped table-bordered dataTable" id="table-triphistory">
                <thead>
                    <tr>
                        <th>Customer Name</th>
                        <th>Booking Number</th>
                        <th>Payment Method</th>
                        <th>Booking Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Customer Name</th>
                        <th>Booking Number</th>
                        <th>Payment Method</th>
                        <th>Booking Status</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script>
    $(document).ready(function(){
        var id = {{$id}};
        $('#table-triphistory').DataTable({
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url":"{{route('admin.ajax-passenger-trips')}}",
                "dataType":"json",
                "type":"POST",
                "data":{ "_token":"<?= csrf_token() ?>",'id': id },
            },
            "columns":[
                {"data":"customer_name"},
                {"data":"booking_number"},
                {"data":"payment_method"},
                {"data":"booking_status"},
                {"data":"action","searchable":false,"orderable":false}
            ],
            responsive: true,
            dom: 'Bfrtip',
            buttons: [
                'copyHtml5',
                'excelHtml5',
                'csvHtml5',
                'pdfHtml5'
            ],
        });
    });
</script>
@endsection