routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('/login');
Route::get('/', 'Admin\Auth\LoginController@showLoginForm')->name('/');
Route::post('/loggedin', 'Admin\Auth\LoginController@login');
Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@otpRequestForm')->name('password.reset');
Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendOTP')->name('password.email');
Route::get('password/otp', 'Admin\Auth\ForgotPasswordController@otpForm')->name('password.otp');
Route::get('password/otpvarify', 'Admin\Auth\ForgotPasswordController@otpVarification')->name('password.otpvarify');
Route::get('password/edit', 'Admin\Auth\ForgotPasswordController@passworUpdateForm')->name('password.edit');
Route::post('password/update', 'Admin\Auth\ForgotPasswordController@updatePassword')->name('password.update');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

	Route::get('driver/document/{id}', 'Driver\DriverController@driverDocument')->name('driver.document');
	Route::get('driver/upload/document/{user_id}/{doc_id}', 'Driver\DriverController@driverDocumentIndex')->name('driver.upload.document');
	Route::post('driver/update/document', 'Driver\DriverController@driverDocumentUpdate')->name('driver.update.document');

	Route::post('logout', 'Auth\LoginController@logout')->name('logout');
	Route::resource('dashboard', 'Dashboard\DashboardController');
	Route::get('dashboard/details/{id}/{param}', 'Dashboard\DashboardController@dashboardRequestDetails')->name('dashboard.details');

	Route::get('password', 'AdminController@password')->name('password');
	Route::post('password/update', 'AdminController@changePassword')->name('password.update');

	Route::get('profile', 'AdminController@profile')->name('profile');
	Route::post('profile/update', 'AdminController@profileUpdate')->name('profile.update');

	Route::resource('setting', 'Setting\SettingController');

	Route::get('settings/payment', 'Setting\SettingController@paymentSetting')->name('settings.payment');

	Route::get('settings/live', 'Setting\SettingController@liveStripe')->name('settings.live');

	Route::get('settings/demo', 'Setting\SettingController@demoStripe')->name('settings.demo');

	Route::get('stripemode/update', 'Setting\SettingController@updateStripeMode')->name('stripemode.update');

	Route::post('settings/payment/update', 'Setting\SettingController@updateStripe')->name('settings.payment.update');

	//banner text..........
	Route::get('settings/banner-text', 'Setting\SettingController@bannerText')->name('settings.banner-text');

	Route::put('settings/banner-text/update/{id}', 'Setting\SettingController@bannerTextUpdate')->name('settings.banner-text.update');
	//..................

	//about us..........
	Route::get('settings/about-us', 'Setting\SettingController@aboutUS')->name('settings.about-us');

	Route::put('settings/about-us/update/{id}', 'Setting\SettingController@aboutUsUpdate')->name('settings.about-us.update');
	//..................

	//app-paragraph..........
	Route::get('settings/app-paragraph', 'Setting\SettingController@appParagraph')->name('settings.app-paragraph');

	Route::put('settings/app-paragraph/update/{id}', 'Setting\SettingController@appParagraphUpdate')->name('settings.app-paragraph.update');
	//..................

	Route::get('privacy/policy', 'Setting\SettingController@privacyPolicy')->name('privacy.policy');
	Route::put('privacy-policy/update/{id}', 'Setting\SettingController@privacyPolicyUpdate')->name('privacy-policy.update');

	Route::resource('document', 'Document\DocumentController');
	Route::get('document/active/{id}', 'Document\DocumentController@changeStatus')->name('document.active');

	Route::resource('service', 'Service\ServiceTypeController');

	Route::resource('vehicle', 'Vehicle\VehicleController');
	Route::post('vehicles','Vehicle\VehicleController@getVehicles')->name('dataProcessing');

	Route::resource('passenger', 'Passenger\PassengerController');
	Route::post('ajax-passenger','Passenger\PassengerController@ajaxPassenger')->name('ajax-passenger');

	Route::get('get/vehicle', 'Driver\DriverController@getVehicle')->name('get.vehicle');

	Route::resource('driver', 'Driver\DriverController');
	Route::post('ajax-driver','Driver\DriverController@ajaxDriver')->name('ajax-driver');

	Route::get('drivers/document/{id}', 'Driver\DriverController@listDriverDocument')->name('drivers.document');
	Route::get('drivers/service-type/{id}', 'Driver\DriverController@listDriverServiceType')->name('drivers.service-type');
	Route::get('driver/document/verification/{id}', 'Driver\DriverController@driverDocumentVerification')->name('driver.document.verification');
	Route::get('driver/activation/{id}', 'Driver\DriverController@driverActivationProcess')->name('driver.activation');
	// Route::get('driver/carimages/{id}', 'Driver\DriverController@driverCarImages')->name('driver.carimages');
	// Route::get('driver/transaction/{id}', 'Driver\DriverController@driverTransaction')->name('driver.transaction');
	Route::post('driver/document-reason/{id}', 'Driver\DriverController@documentVerificationReason')->name('driver.document-reason');

	Route::get('request/all', 'DriveReport\DriveReportController@allRequest')->name('request.all');
	Route::post('ajax-all-request', 'DriveReport\DriveReportController@ajaxAllRequest')->name('ajax-all-request');
	Route::get('request/nofound', 'DriveReport\DriveReportController@noServiceFoundRequest')->name('request.nofound');
	Route::post('ajax-noservice-found', 'DriveReport\DriveReportController@ajaxNoServiceFoundRequest')->name('ajax-noservice-found');

	Route::get('request/rejected', 'DriveReport\DriveReportController@rejectedRequest')->name('request.rejected');
	Route::post('ajax-rejected-request', 'DriveReport\DriveReportController@ajaxRejectedRequest')->name('ajax-rejected-request');

	Route::get('request/schedule', 'DriveReport\DriveReportController@scheduleRequest')->name('request.schedule');
	Route::post('ajax-schedule-request', 'DriveReport\DriveReportController@ajaxScheduleRequest')->name('ajax-schedule-request');

	Route::get('request/details/{id}/{param}', 'DriveReport\DriveReportController@requestDetails')->name('request.details');

	Route::get('chat/support', 'Chat\ChatSupportController@chatSupport')->name('chat.support');

	 //report issue
	Route::get('reportIssue/driver/subject/list', 'ReportIssue\ReportController@driverSubjectList')->name('reportIssue.driver.subject.list');
	Route::post('reportIssue/driver/subject/add', 'ReportIssue\ReportController@driverSubjectAdd')->name('reportIssue.driver.subject.add');
	Route::get('reportIssue/driver/subject/edit/{id}', 'ReportIssue\ReportController@driverSubjectEdit')->name('reportIssue.driver.subject.edit');
	Route::put('reportIssue/driver/subject/update/{id}', 'ReportIssue\ReportController@driverSubjectUpdate')->name('reportIssue.driver.subject.update');

	Route::get('reportIssue/customer/subject/list', 'ReportIssue\ReportController@customerSubjectList')->name('reportIssue.customer.subject.list');
	Route::post('reportIssue/customer/subject/add', 'ReportIssue\ReportController@customerSubjectAdd')->name('reportIssue.customer.subject.add');
	Route::get('reportIssue/customer/subject/edit/{id}', 'ReportIssue\ReportController@customerSubjectEdit')->name('reportIssue.customer.subject.edit');
	Route::put('reportIssue/customer/subject/update/{id}', 'ReportIssue\ReportController@customerSubjectUpdate')->name('reportIssue.customer.subject.update');

	Route::get('reportIssue/driver/list', 'ReportIssue\ReportController@driverReportIssueList')->name('reportIssue.driver.list');
	Route::get('reportIssue/customer/list', 'ReportIssue\ReportController@customerReportIssueList')->name('reportIssue.customer.list');
	Route::get('reportIssue/details/{id}/{param}', 'ReportIssue\ReportController@reportIssueDetails')->name('reportIssue.details');
	// Route::get('reportIssue/customer/details/{id}/{param}', 'ReportIssue\ReportController@customerReportIssueDetails')->name('reportIssue.customer.details');

	//review rating
	Route::get('drivers/review-rating/{id}', 'Driver\DriverController@driverRatingReview')->name('drivers.review-rating');
	Route::get('passenger/review-rating/{id}', 'Passenger\PassengerController@passengerRatingReview')->name('passenger.review-rating');

	//passenger trip
	Route::get('passenger/trip/history/{id}', 'Passenger\TripController@tripIndex')->name("passenger.trip.history");
	Route::post('ajax-passenger-trips', 'Passenger\TripController@ajaxPassengerTrips')->name('ajax-passenger-trips');
	Route::get('passenger/trip/history/details/{id}/{param}', 'Passenger\TripController@tripDetails')->name('passenger.trip.history.details');

	 //Driver trip
	Route::get('driver/trip/history/{id}', 'Driver\DriverTripController@tripIndex')->name("driver.trip.history");
	Route::post('ajax-driver-trips', 'Driver\DriverTripController@ajaxDriverTrips')->name('ajax-driver-trips');
	Route::get('driver/trip/history/details/{id}/{param}', 'Driver\DriverTripController@tripDetails')->name('driver.trip.history.details');

	Route::resource('promocode', 'Promocode\PromocodeController');

	//make model year
	Route::get('get/admin/make', 'Driver\DriverController@getAdminMake')->name("get.admin.make");
	Route::post('get/admin/model', 'Driver\DriverController@getAdminModel')->name("get.admin.model");
	Route::post('get/admin/year', 'Driver\DriverController@getAdminYear')->name("get.admin.year");
	

resources/views/admin/setting/about-us.blade.php
@extends('admin.layout.base')

@section('title', 'About Us')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5>About Us</h5>

            <div className="row">
                <form action="{{ route('admin.settings.about-us.update',$aboutUS->id) }}" method="POST">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT">

                    <div class="row">
                        <div class="col-xs-12">
                            <textarea name="value" id="myeditor">{{$aboutUS->value}}</textarea>
                        </div>
                    </div>

                    <br>
                    <div class="row">
                        <div class="col-xs-10">
                            <button type="submit" class="btn btn-primary">Update</button>
                            <a href="{{route('admin.dashboard.index')}}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
@endsection

@section('scripts')
<script src="//cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>
<script type="text/javascript">
    CKEDITOR.replace('myeditor');
</script>
@endsection

resources/views/admin/setting/app-paragraph.blade.php
@extends('admin.layout.base')

@section('title', 'App Paragraph')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5>App Paragraph</h5>

            <div className="row">
                <form action="{{ route('admin.settings.app-paragraph.update',$appParagraph->id) }}" method="POST">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT">

                    <div class="row">
                        <div class="col-xs-12">
                            <textarea name="value" id="myeditor">{{$appParagraph->value}}</textarea>
                        </div>
                    </div>

                    <br>
                    <div class="row">
                        <div class="col-xs-10">
                            <button type="submit" class="btn btn-primary">Update</button>
                            <a href="{{route('admin.dashboard.index')}}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
@endsection

@section('scripts')
<script src="//cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>
<script type="text/javascript">
    CKEDITOR.replace('myeditor');
</script>
@endsection

resources/views/admin/setting/banner-text.blade.php
@extends('admin.layout.base')

@section('title', 'Banner Text')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5>First Banner Text</h5>

            @foreach($bannerText as $banner)
            @if($banner->key == 'web_banner_text_one')
            <div className="row">
                <form action="{{ route('admin.settings.banner-text.update',$banner->id) }}" method="POST">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT">

                    <div class="row">
                        <div class="col-xs-12">
                            <textarea name="value" id="myeditor">{{$banner->value}}</textarea>
                        </div>
                    </div>

                    <br>
                    <div class="row">
                        <div class="col-xs-10">
                            <button type="submit" class="btn btn-primary">Update</button>
                            <a href="{{route('admin.dashboard.index')}}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
            @endif
            @endforeach

        </div>
    </div>
</div>
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5>Second Banner Text</h5>

            @foreach($bannerText as $banner)
            @if($banner->key == 'web_banner_text_two')
            <div className="row">
                <form action="{{ route('admin.settings.banner-text.update',$banner->id) }}" method="POST">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT">

                    <div class="row">
                        <div class="col-xs-12">
                            <textarea name="value" id="myeditor1">{{$banner->value}}</textarea>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-xs-10">
                            <button type="submit" class="btn btn-primary">Update</button>
                            <a href="{{route('admin.dashboard.index')}}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
            @endif
            @endforeach

        </div>
    </div>
</div>
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5>Third Banner Text</h5>

            @foreach($bannerText as $banner)
            @if($banner->key == 'web_banner_text_three')
            <div className="row">
                <form action="{{ route('admin.settings.banner-text.update',$banner->id) }}" method="POST">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT">

                    <div class="row">
                        <div class="col-xs-12">
                            <textarea name="value" id="myeditor2">{{$banner->value}}</textarea>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-xs-10">
                            <button type="submit" class="btn btn-primary">Update</button>
                            <a href="{{route('admin.dashboard.index')}}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
            @endif
            @endforeach

        </div>
    </div>
</div>
@endsection

@section('scripts')
<script src="//cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>
<script type="text/javascript">
    CKEDITOR.replace('myeditor');
    CKEDITOR.replace('myeditor1');
    CKEDITOR.replace('myeditor2');
</script>
@endsection

resources/views/admin/setting/edit.blade.php
@extends('admin.layout.base')

@section('title', 'Update Site Setting')

@section('content')

<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <a href="{{ route('admin.setting.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>

            <h5 style="margin-bottom: 2em;">Update Site Setting</h5>

            <form class="form-horizontal" action="{{route('admin.setting.update', $site_setting->id )}}" method="POST" enctype="multipart/form-data" role="form">

                {{csrf_field()}}
                <input type="hidden" name="_method" value="PATCH">
                <div class="form-group row">
                    <label for="key" class="col-xs-2 col-form-label">Name</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="text" value="{{ $site_setting->key }}" name="key" id="key" placeholder="Key" readonly>
                    </div>
                </div>
                @if($site_setting->key == 'site_title'||$site_setting->key == 'site_copyright'||$site_setting->key == 'web_site')
                <div class="form-group row">
                    <label for="value" class="col-xs-2 col-form-label">Value</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="text" value="{{ $site_setting->value }}" name="value"  id="value" placeholder="Value" required>
                    </div>
                </div>
                @elseif($site_setting->key == 'contact_email')
                <div class="form-group row">
                    <label for="value" class="col-xs-2 col-form-label">Value</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="email" value="{{ $site_setting->value }}" name="value"  id="value" placeholder="Value" required>
                    </div>
                </div>
                @elseif($site_setting->key == 'contact_number'||$site_setting->key == 'sos_number')
                <div class="form-group row">
                    <label for="value" class="col-xs-2 col-form-label">Value</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="number" value="{{ $site_setting->value }}" name="value"  id="value" placeholder="Value" required>
                    </div>
                </div>

                @elseif($site_setting->key == 'site_logo'||$site_setting->key == 'site_email_logo'||$site_setting->key == 'site_icon')
                <div class="form-group row">
                    <label for="value" class="col-xs-2 col-form-label">Logo</label>
                    <div class="col-xs-10">
                    @if(isset($site_setting->value))
                        @if(File::exists(storage_path('app/public' .str_replace("storage", "", $site_setting->value))))
                        <img style="height: 90px; margin-bottom: 15px;" src="{{URL::asset($site_setting->value)}}">
                        @else
                        <img style="height: 60px; margin-bottom: 15px;" src="{{URL::asset('asset/NO_IMG.png')}}">
                        @endif
                    @else
                        <img style="height: 60px; margin-bottom: 15px;" src="{{URL::asset('asset/NO_IMG.png')}}">
                    @endif
                        <input type="file" accept="image/*" name="value" class="dropify form-control-file" id="value" aria-describedby="fileHelp">
                    </div>
                </div>
                @endif

                <div class="form-group row">
                    <label for="zipcode" class="col-xs-2 col-form-label"></label>
                    <div class="col-xs-10">
                        <button type="submit" class="btn btn-primary">Update Site Setting</button>
                        <a href="{{route('admin.setting.index')}}" class="btn btn-default">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/setting/payment.blade.php
@extends('admin.layout.base')
@section('title', 'Payment Setting')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5 class="mb-1">Payment Setting</h5>

            <div class="form-group row">
                <div class="col-xs-4"></div>

                <div class="col-xs-6">
                    <div class="onoffswitch">
                        <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox stripe_check" id="myonoffswitch" tabindex="0" onchange="cardselect()">
                        <label class="onoffswitch-label" for="myonoffswitch">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>

            <form id="stripe_field">
               
                    <input type="hidden" name="type" id="type">

                    <div class="form-group row">
                        <label for="stripe_secret_key" class="col-xs-4 col-form-label">Stripe Secret key</label>
                        <div class="col-xs-8">
                            <input class="form-control" type="text" value="" name="stripe_secret_key" id="stripe_secret_key"  placeholder="Stripe Secret key">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="stripe_publishable_key" class="col-xs-4 col-form-label">Stripe Publishable key</label>
                        <div class="col-xs-8">
                            <input class="form-control" type="text" value="" name="stripe_publishable_key" id="stripe_publishable_key"  placeholder="Stripe Publishable key">
                        </div>
                    </div>

                <div class="form-group row">
                    <label for="zipcode" class="col-xs-4 col-form-label"></label>
                    <div class="col-xs-8">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a href="{{route('admin.dashboard.index')}}" class="btn btn-default">Cancel</a>
                    </div>
                </div>
            </form>
           
        </div>
    </div>
</div>
<style>
    .onoffswitch {
        position: relative; width: 90px;
        -webkit-user-select:none; -moz-user-select:none; -ms-user-select: none;
    }
    .onoffswitch-checkbox {
        position: absolute;
        opacity: 0;
        pointer-events: none;
    }
    .onoffswitch-label {
        display: block; overflow: hidden; cursor: pointer;
        border: 2px solid #999999; border-radius: 20px;
    }
    .onoffswitch-inner {
        display: block; width: 200%; margin-left: -100%;
        transition: margin 0.3s ease-in 0s;
    }
    .onoffswitch-inner:before, .onoffswitch-inner:after {
        display: block; float: left; width: 50%; height: 30px; padding: 0; line-height: 30px;
        font-size: 14px; color: white; font-family: Trebuchet, Arial, sans-serif; font-weight: bold;
        box-sizing: border-box;
    }
    .onoffswitch-inner:before {
        content: "Live";
        padding-left: 10px;
        background-color: #0da612; color: #FFFFFF;
    }
    .onoffswitch-inner:after {
        content: "Demo";
        padding-right: 10px;
        background-color: dimgrey; color: linen;
        text-align: right;
    }
    .onoffswitch-switch {
        display: block;
        width: 18px;
        background: #FFFFFF;
        position: absolute;
        top: 0;
        bottom: 0;
        border: 2px solid #999999; border-radius: 20px;
        transition: all 0.3s ease-in 0s;

        margin-bottom: 5px;
        margin-top: 3px;
        margin-right: 6px;
        margin-left: 6px;
    }
    .onoffswitch-checkbox:checked + .onoffswitch-label .onoffswitch-inner {
        margin-left: 0;
    }
    .onoffswitch-checkbox:checked + .onoffswitch-label .onoffswitch-switch {
        right: 0px;
</style>
@endsection
@section('scripts')
<script>
    $.ajax({
        url: "{{ route('admin.settings.demo') }}",
        method: "GET",
        data: {},
        success: function(response){
            $('#stripe_secret_key').val(response.data[1].value);
            $('#stripe_publishable_key').val(response.data[0].value);
            $('#type').val('demo');
            var type = 'demo';
            $.ajax({
                url: "{{ route('admin.stripemode.update') }}",
                method: "GET",
                data: {type:type},
                success: function(response){
                }
            });
        },
        error: function(response){
           console.log(response);
        }
    });

    function cardselect()
    {
        if($('.stripe_check').is(":checked")) {
            $('.success_alert').hide();
            $.ajax({
                url: "{{ route('admin.settings.live') }}",
                method: "GET",
                data: {},
                success: function(response){
                    $('#stripe_secret_key').val(response.data[1].value);
                    $('#stripe_publishable_key').val(response.data[0].value);
                    $('#type').val('live');
                    var type = 'live';
                    $.ajax({
                        url: "{{ route('admin.stripemode.update') }}",
                        method: "GET",
                        data: {type:type},
                        success: function(response){
                        }
                    });
                },
                error: function(response){
                   console.log(response);
                }
            });
        } else {
            $('.success_alert').hide();
            $.ajax({
                url: "{{ route('admin.settings.demo') }}",
                method: "GET",
                data: {},
                success: function(response){
                    $('#stripe_secret_key').val(response.data[1].value);
                    $('#stripe_publishable_key').val(response.data[0].value);
                    $('#type').val('demo');
                    var type = 'demo';
                    $.ajax({
                        url: "{{ route('admin.stripemode.update') }}",
                        method: "GET",
                        data: {type:type},
                        success: function(response){
                        }
                    });
                },
                error: function(response){
                   console.log(response);
                }
            });
        }
    }

    $('#stripe_field').on('submit', function(event){
        event.preventDefault();
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        var type = $('#type').val();
        var stripe_secret_key = $('#stripe_secret_key').val();
        var stripe_publishable_key = $('#stripe_publishable_key').val();
        $.ajax({
            url: "{{ route('admin.settings.payment.update') }}",
            method:"POST",
            data:{ type: type, stripe_secret_key: stripe_secret_key, stripe_publishable_key: stripe_publishable_key },
            success: function(response){
                $('#stripe_secret_key').val(response.data[1].value);
                $('#stripe_publishable_key').val(response.data[0].value);
                $('.success_alert').show();
                $('.success_msg').text(response.message);
            },
            error: function(response){
                console.log(response);
            }

        });
    });

</script>
@endsection

resources/views/admin/setting/policy.blade.php
@extends('admin.layout.base')

@section('title', 'Privacy Policy ')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5>Privacy Policy</h5>

            @foreach($policies as $policy)
            @if($policy->key == 'page_privacy')
            <div className="row">
                <form action="{{ route('admin.privacy-policy.update',$policy->id) }}" method="POST">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT">

                    <div class="row">
                        <div class="col-xs-12">
                            <textarea name="value" id="myeditor">{{$policy->value}}</textarea>
                        </div>
                    </div>

                    <br>
                    <div class="row">
                        <div class="col-xs-10">
                            <button type="submit" class="btn btn-primary">Update</button>
                            <a href="{{route('admin.dashboard.index')}}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
            @endif
            @endforeach

        </div>
    </div>
</div>
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5>Terms and Conditions</h5>

            @foreach($policies as $policy)
            @if($policy->key == 'condition_privacy')
            <div className="row">
                <form action="{{ route('admin.privacy-policy.update',$policy->id) }}" method="POST">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT">

                    <div class="row">
                        <div class="col-xs-12">
                            <textarea name="value" id="myeditor1">{{$policy->value}}</textarea>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-xs-10">
                            <button type="submit" class="btn btn-primary">Update</button>
                            <a href="{{route('admin.dashboard.index')}}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
            @endif
            @endforeach

        </div>
    </div>
</div>
@endsection

@section('scripts')
<script src="//cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>
<script type="text/javascript">
    CKEDITOR.replace('myeditor');
</script>
<script type="text/javascript">
    CKEDITOR.replace('myeditor1');
</script>
@endsection